# Basic formatting options
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"

# Width settings
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50

# Comment formatting
wrap_comments = false
format_code_in_doc_comments = false

# Import formatting
reorder_imports = true
reorder_modules = true

# Control flow formatting
remove_nested_parens = true
short_array_element_width_threshold = 10

# Match formatting
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false

# Function formatting
fn_params_layout = "Tall"

# Edition
edition = "2021"

# Other options
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true