//! NetworkBehaviour definition for the state node.
//!
//! Combines multiple libp2p protocols:
//! - Kademlia DHT for peer discovery and content routing
//! - Gossipsub for event propagation
//! - RequestResponse for direct peer communication
//! - mDNS for local peer discovery
//! - Identify for peer identification

use super::protocol::{ContentRequest, ContentResponse};
use super::public_key_protocol::{PublicKeyRequest, PublicKeyResponse};
use libp2p::{
    autonat, dcutr, gossipsub, identify, kad, relay,
    request_response::{self, ProtocolSupport},
    swarm::{behaviour::toggle::Toggle, NetworkBehaviour},
    StreamProtocol,
};
use std::time::Duration;

#[cfg(not(target_arch = "wasm32"))]
use libp2p::mdns;

/// Protocol name for content requests.
pub const CONTENT_PROTOCOL_NAME: &str = "/monas/content/1.0.0";

/// Protocol name for public key exchange.
pub const PUBLIC_KEY_PROTOCOL_NAME: &str = "/monas/public-key/1.0.0";

/// Simultaneous relay reservations this node will hold for others.
///
/// A reservation costs a slot and some memory, and relaying is a favour done
/// for peers we may know nothing about, so it is capped. Reached only on a
/// node that many private peers picked as their relay.
const MAX_RELAY_RESERVATIONS: usize = 128;

/// Simultaneous relayed circuits carried for others.
///
/// Circuits carry real traffic, so this is the tighter of the two limits.
/// DCUtR normally promotes a circuit to a direct connection shortly after it
/// is established, which is what keeps this number small in practice.
const MAX_RELAY_CIRCUITS: usize = 32;

/// Combined network behaviour for the state node.
#[derive(NetworkBehaviour)]
#[behaviour(to_swarm = "NodeBehaviourEvent")]
pub struct NodeBehaviour {
    /// Kademlia DHT for peer discovery and content routing.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Gossipsub for event propagation.
    pub gossipsub: gossipsub::Behaviour,
    /// RequestResponse for direct peer communication.
    pub request_response: request_response::cbor::Behaviour<ContentRequest, ContentResponse>,
    /// RequestResponse for public key exchange.
    pub public_key_protocol: request_response::cbor::Behaviour<PublicKeyRequest, PublicKeyResponse>,
    /// Identify for peer identification.
    pub identify: identify::Behaviour,
    /// mDNS for local peer discovery (native only), off when disabled in the
    /// config — see `BehaviourConfig::enable_mdns`.
    #[cfg(not(target_arch = "wasm32"))]
    pub mdns: Toggle<mdns::tokio::Behaviour>,
    /// AutoNAT v2 client: asks other nodes to dial us back so we learn whether
    /// we are actually reachable, instead of assuming it.
    pub autonat_client: Toggle<autonat::v2::client::Behaviour>,
    /// AutoNAT v2 server: answers those requests for other nodes.
    pub autonat_server: Toggle<autonat::v2::server::Behaviour>,
    /// Circuit relay v2 server — lets other nodes reach peers we can reach.
    /// Only enabled once we believe we are publicly reachable.
    pub relay_server: Toggle<relay::Behaviour>,
    /// Circuit relay v2 client — used when we cannot be dialled directly.
    pub relay_client: Toggle<relay::client::Behaviour>,
    /// DCUtR: upgrades a relayed connection to a direct one via hole punching,
    /// so the relay is only needed to get started.
    pub dcutr: Toggle<dcutr::Behaviour>,
}

/// Events generated by the combined behaviour.
#[derive(Debug)]
pub enum NodeBehaviourEvent {
    Kademlia(kad::Event),
    Gossipsub(Box<gossipsub::Event>),
    RequestResponse(request_response::Event<ContentRequest, ContentResponse>),
    PublicKeyProtocol(request_response::Event<PublicKeyRequest, PublicKeyResponse>),
    Identify(Box<identify::Event>),
    #[cfg(not(target_arch = "wasm32"))]
    Mdns(mdns::Event),
    AutonatClient(autonat::v2::client::Event),
    AutonatServer(autonat::v2::server::Event),
    RelayServer(Box<relay::Event>),
    RelayClient(relay::client::Event),
    Dcutr(dcutr::Event),
}

impl From<kad::Event> for NodeBehaviourEvent {
    fn from(event: kad::Event) -> Self {
        NodeBehaviourEvent::Kademlia(event)
    }
}

impl From<gossipsub::Event> for NodeBehaviourEvent {
    fn from(event: gossipsub::Event) -> Self {
        NodeBehaviourEvent::Gossipsub(Box::new(event))
    }
}

impl From<request_response::Event<ContentRequest, ContentResponse>> for NodeBehaviourEvent {
    fn from(event: request_response::Event<ContentRequest, ContentResponse>) -> Self {
        NodeBehaviourEvent::RequestResponse(event)
    }
}

impl From<request_response::Event<PublicKeyRequest, PublicKeyResponse>> for NodeBehaviourEvent {
    fn from(event: request_response::Event<PublicKeyRequest, PublicKeyResponse>) -> Self {
        NodeBehaviourEvent::PublicKeyProtocol(event)
    }
}

impl From<identify::Event> for NodeBehaviourEvent {
    fn from(event: identify::Event) -> Self {
        NodeBehaviourEvent::Identify(Box::new(event))
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl From<mdns::Event> for NodeBehaviourEvent {
    fn from(event: mdns::Event) -> Self {
        NodeBehaviourEvent::Mdns(event)
    }
}

impl From<autonat::v2::client::Event> for NodeBehaviourEvent {
    fn from(event: autonat::v2::client::Event) -> Self {
        NodeBehaviourEvent::AutonatClient(event)
    }
}

impl From<autonat::v2::server::Event> for NodeBehaviourEvent {
    fn from(event: autonat::v2::server::Event) -> Self {
        NodeBehaviourEvent::AutonatServer(event)
    }
}

impl From<relay::Event> for NodeBehaviourEvent {
    fn from(event: relay::Event) -> Self {
        NodeBehaviourEvent::RelayServer(Box::new(event))
    }
}

impl From<relay::client::Event> for NodeBehaviourEvent {
    fn from(event: relay::client::Event) -> Self {
        NodeBehaviourEvent::RelayClient(event)
    }
}

impl From<dcutr::Event> for NodeBehaviourEvent {
    fn from(event: dcutr::Event) -> Self {
        NodeBehaviourEvent::Dcutr(event)
    }
}

/// Configuration for creating a NodeBehaviour.
#[derive(Debug, Clone)]
pub struct BehaviourConfig {
    /// Protocol version string.
    pub protocol_version: String,
    /// Agent version string.
    pub agent_version: String,
    /// Enable mDNS local-network peer discovery.
    ///
    /// mDNS only works within a broadcast domain, so it is useless in most
    /// real deployments (an ECS/VPC or cross-internet network never sees it)
    /// but very effective locally — effective enough to mask bugs in the
    /// discovery paths that production actually depends on. Being able to turn
    /// it off is what lets a local 4-node cluster reproduce production
    /// conditions.
    pub enable_mdns: bool,
    /// Enable NAT traversal: AutoNAT v2 reachability probing, circuit relay v2
    /// and DCUtR hole punching.
    ///
    /// This is what allows a node behind NAT to take part at all. It is
    /// deliberately separable so a deployment of publicly reachable nodes —
    /// which needs none of it — can leave the machinery off.
    pub enable_nat_traversal: bool,
}

impl Default for BehaviourConfig {
    fn default() -> Self {
        Self {
            protocol_version: "/monas/1.0.0".to_string(),
            agent_version: format!("monas-state-node/{}", env!("CARGO_PKG_VERSION")),
            enable_mdns: true,
            enable_nat_traversal: true,
        }
    }
}

impl NodeBehaviour {
    /// Create a new NodeBehaviour with the given peer ID and configuration.
    /// `relay_client` must be the behaviour half returned by
    /// `relay::client::new` alongside the transport that was passed to
    /// `transport::build_transport_with_relay`. Passing `None` disables
    /// relayed dialling even when `enable_nat_traversal` is set — the two
    /// halves only work as a pair.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn new(
        local_peer_id: libp2p::PeerId,
        keypair: &libp2p::identity::Keypair,
        config: BehaviourConfig,
        relay_client: Option<relay::client::Behaviour>,
    ) -> anyhow::Result<Self> {
        // Kademlia configuration
        let mut kad_config = kad::Config::new(StreamProtocol::new("/monas/kad/1.0.0"));
        kad_config.set_query_timeout(Duration::from_secs(60));
        let store = kad::store::MemoryStore::new(local_peer_id);
        let mut kademlia = kad::Behaviour::with_config(local_peer_id, store, kad_config);
        // Enable server mode so this node responds to Kademlia queries from other peers
        kademlia.set_mode(Some(kad::Mode::Server));

        // Gossipsub configuration
        let gossipsub_config = gossipsub::ConfigBuilder::default()
            .heartbeat_interval(Duration::from_secs(1))
            .validation_mode(gossipsub::ValidationMode::Strict)
            .build()
            .map_err(|e| anyhow::anyhow!("Failed to create gossipsub config: {}", e))?;

        let gossipsub = gossipsub::Behaviour::new(
            gossipsub::MessageAuthenticity::Signed(keypair.clone()),
            gossipsub_config,
        )
        .map_err(|e| anyhow::anyhow!("Failed to create gossipsub behaviour: {}", e))?;

        // RequestResponse configuration using CBOR codec
        // Apply request timeout and limit concurrent streams to mitigate DoS
        let rr_config = request_response::Config::default()
            .with_request_timeout(Duration::from_secs(30))
            .with_max_concurrent_streams(32);
        let request_response = request_response::cbor::Behaviour::new(
            [(
                StreamProtocol::new(CONTENT_PROTOCOL_NAME),
                ProtocolSupport::Full,
            )],
            rr_config,
        );

        // Public key protocol configuration using CBOR codec
        let pk_config = request_response::Config::default()
            .with_request_timeout(Duration::from_secs(15))
            .with_max_concurrent_streams(16);
        let public_key_protocol = request_response::cbor::Behaviour::new(
            [(
                StreamProtocol::new(PUBLIC_KEY_PROTOCOL_NAME),
                ProtocolSupport::Full,
            )],
            pk_config,
        );

        // Identify configuration
        let identify = identify::Behaviour::new(identify::Config::new(
            config.protocol_version,
            keypair.public(),
        ));

        // mDNS configuration
        let mdns: Toggle<mdns::tokio::Behaviour> = if config.enable_mdns {
            Some(mdns::tokio::Behaviour::new(
                mdns::Config::default(),
                local_peer_id,
            )?)
        } else {
            None
        }
        .into();

        // NAT traversal.
        //
        // Both AutoNAT roles are enabled together on purpose. A node cannot
        // know in advance which side it will be on, and a network where only
        // some nodes answer probes degrades for everyone: reachability is a
        // service peers provide to each other, like relaying.
        //
        // The relay *server* is created here but only ever used once AutoNAT
        // reports us as reachable (see libp2p_network.rs). Relaying from
        // behind NAT would not work anyway, and advertising it would waste
        // other nodes' reservation attempts.
        let (autonat_client, autonat_server, relay_server, dcutr) = if config.enable_nat_traversal {
            (
                Some(autonat::v2::client::Behaviour::new(
                    rand::rngs::OsRng,
                    autonat::v2::client::Config::default(),
                )),
                Some(autonat::v2::server::Behaviour::new(rand::rngs::OsRng)),
                Some(relay::Behaviour::new(
                    local_peer_id,
                    // Bound what a relay will carry. Relaying is done for
                    // strangers, so the limits are what stop it from becoming
                    // free bandwidth for anyone who asks.
                    relay::Config {
                        max_reservations: MAX_RELAY_RESERVATIONS,
                        max_circuits: MAX_RELAY_CIRCUITS,
                        ..Default::default()
                    },
                )),
                Some(dcutr::Behaviour::new(local_peer_id)),
            )
        } else {
            (None, None, None, None)
        };

        // The client half is only meaningful when its transport half was built
        // too, so it is threaded in from the caller rather than created here.
        let relay_client = if config.enable_nat_traversal {
            relay_client
        } else {
            None
        };

        Ok(Self {
            kademlia,
            gossipsub,
            request_response,
            public_key_protocol,
            identify,
            mdns,
            autonat_client: autonat_client.into(),
            autonat_server: autonat_server.into(),
            relay_server: relay_server.into(),
            relay_client: relay_client.into(),
            dcutr: dcutr.into(),
        })
    }

    /// Create a new NodeBehaviour for WASM (without mDNS).
    #[cfg(target_arch = "wasm32")]
    pub fn new(
        local_peer_id: libp2p::PeerId,
        keypair: &libp2p::identity::Keypair,
        config: BehaviourConfig,
    ) -> anyhow::Result<Self> {
        // Kademlia configuration
        let mut kad_config = kad::Config::new(StreamProtocol::new("/monas/kad/1.0.0"));
        kad_config.set_query_timeout(Duration::from_secs(60));
        let store = kad::store::MemoryStore::new(local_peer_id);
        let mut kademlia = kad::Behaviour::with_config(local_peer_id, store, kad_config);
        // Enable server mode so this node responds to Kademlia queries from other peers
        kademlia.set_mode(Some(kad::Mode::Server));

        // Gossipsub configuration
        let gossipsub_config = gossipsub::ConfigBuilder::default()
            .heartbeat_interval(Duration::from_secs(1))
            .validation_mode(gossipsub::ValidationMode::Strict)
            .build()
            .map_err(|e| anyhow::anyhow!("Failed to create gossipsub config: {}", e))?;

        let gossipsub = gossipsub::Behaviour::new(
            gossipsub::MessageAuthenticity::Signed(keypair.clone()),
            gossipsub_config,
        )
        .map_err(|e| anyhow::anyhow!("Failed to create gossipsub behaviour: {}", e))?;

        // RequestResponse configuration using CBOR codec
        // Apply request timeout and limit concurrent streams to mitigate DoS
        let rr_config = request_response::Config::default()
            .with_request_timeout(Duration::from_secs(30))
            .with_max_concurrent_streams(32);
        let request_response = request_response::cbor::Behaviour::new(
            [(
                StreamProtocol::new(CONTENT_PROTOCOL_NAME),
                ProtocolSupport::Full,
            )],
            rr_config,
        );

        // Public key protocol configuration using CBOR codec
        let pk_config = request_response::Config::default()
            .with_request_timeout(Duration::from_secs(15))
            .with_max_concurrent_streams(16);
        let public_key_protocol = request_response::cbor::Behaviour::new(
            [(
                StreamProtocol::new(PUBLIC_KEY_PROTOCOL_NAME),
                ProtocolSupport::Full,
            )],
            pk_config,
        );

        // Identify configuration
        let identify = identify::Behaviour::new(identify::Config::new(
            config.protocol_version,
            keypair.public(),
        ));

        Ok(Self {
            kademlia,
            gossipsub,
            request_response,
            public_key_protocol,
            identify,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use libp2p::identity::Keypair;

    #[test]
    fn test_content_protocol_name() {
        assert_eq!(CONTENT_PROTOCOL_NAME, "/monas/content/1.0.0");
    }

    #[test]
    fn test_behaviour_config_default() {
        let config = BehaviourConfig::default();

        assert_eq!(config.protocol_version, "/monas/1.0.0");
        assert!(config.agent_version.starts_with("monas-state-node/"));
    }

    #[test]
    fn test_behaviour_config_clone() {
        let config = BehaviourConfig {
            protocol_version: "/custom/1.0.0".to_string(),
            agent_version: "custom-agent/1.0.0".to_string(),
            enable_mdns: true,
            enable_nat_traversal: false,
        };

        let cloned = config.clone();

        assert_eq!(cloned.protocol_version, "/custom/1.0.0");
        assert_eq!(cloned.agent_version, "custom-agent/1.0.0");
    }

    #[test]
    fn test_behaviour_config_debug() {
        let config = BehaviourConfig::default();
        let debug_str = format!("{:?}", config);

        assert!(debug_str.contains("BehaviourConfig"));
        assert!(debug_str.contains("protocol_version"));
        assert!(debug_str.contains("agent_version"));
    }

    #[test]
    fn test_node_behaviour_event_debug() {
        // Test that NodeBehaviourEvent implements Debug
        // We can't easily create kad::Event, gossipsub::Event, etc. in tests,
        // but we can verify the enum variants exist and the type is Debug
        fn assert_debug<T: std::fmt::Debug>() {}
        assert_debug::<NodeBehaviourEvent>();
    }

    /// `enable_mdns` has to actually reach the behaviour.
    ///
    /// It used to be a config field that nothing read: mDNS was constructed
    /// unconditionally, so a local cluster kept rediscovering peers by
    /// broadcast even when the discovery paths a deployment depends on were
    /// broken. That made local runs unable to reproduce production, which is
    /// how an outage went unnoticed until it hit the real network.
    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn mdns_is_absent_when_disabled_and_present_when_enabled() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();

        let off = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig {
                enable_mdns: false,
                ..BehaviourConfig::default()
            },
            None,
        )
        .unwrap();
        assert!(
            off.mdns.as_ref().is_none(),
            "enable_mdns=false must not construct an mDNS behaviour"
        );

        let on = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig {
                enable_mdns: true,
                ..BehaviourConfig::default()
            },
            None,
        )
        .unwrap();
        assert!(
            on.mdns.as_ref().is_some(),
            "enable_mdns=true must enable it"
        );
    }

    /// The NAT-traversal behaviours must follow the flag, both ways.
    ///
    /// Same failure mode as `enable_mdns`, which sat in the config being read
    /// by nobody: a flag that silently does nothing is worse than no flag,
    /// because it makes a deployment look configurable when it is not.
    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn nat_traversal_behaviours_follow_the_flag() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();

        let off = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig {
                enable_nat_traversal: false,
                ..BehaviourConfig::default()
            },
            None,
        )
        .unwrap();
        assert!(off.autonat_client.as_ref().is_none());
        assert!(off.autonat_server.as_ref().is_none());
        assert!(off.relay_server.as_ref().is_none());
        assert!(off.dcutr.as_ref().is_none());

        let on = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig {
                enable_nat_traversal: true,
                ..BehaviourConfig::default()
            },
            None,
        )
        .unwrap();
        assert!(on.autonat_client.as_ref().is_some());
        assert!(on.autonat_server.as_ref().is_some());
        assert!(on.relay_server.as_ref().is_some());
        assert!(on.dcutr.as_ref().is_some());
    }

    /// The relay client only exists when its transport half was built too.
    ///
    /// `relay::client::new` returns a transport and a behaviour that are
    /// useless apart: the behaviour negotiates a reservation the transport
    /// would then have to dial through. Enabling one without the other would
    /// advertise a circuit address nothing can actually dial.
    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn relay_client_is_absent_unless_its_transport_half_is_supplied() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();

        let without =
            NodeBehaviour::new(local_peer_id, &keypair, BehaviourConfig::default(), None).unwrap();
        assert!(without.relay_client.as_ref().is_none());

        let (_transport, client) = relay::client::new(local_peer_id);
        let with = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig::default(),
            Some(client),
        )
        .unwrap();
        assert!(with.relay_client.as_ref().is_some());
    }

    /// Passing a relay client while NAT traversal is off must not enable it.
    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn relay_client_is_ignored_when_nat_traversal_is_disabled() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();

        let (_transport, client) = relay::client::new(local_peer_id);
        let behaviour = NodeBehaviour::new(
            local_peer_id,
            &keypair,
            BehaviourConfig {
                enable_nat_traversal: false,
                ..BehaviourConfig::default()
            },
            Some(client),
        )
        .unwrap();
        assert!(behaviour.relay_client.as_ref().is_none());
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn test_node_behaviour_creation() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();
        let config = BehaviourConfig::default();

        let result = NodeBehaviour::new(local_peer_id, &keypair, config, None);

        assert!(result.is_ok());
        let behaviour = result.unwrap();

        // Verify components are accessible
        let _ = &behaviour.kademlia;
        let _ = &behaviour.gossipsub;
        let _ = &behaviour.request_response;
        let _ = &behaviour.public_key_protocol;
        let _ = &behaviour.identify;
        let _ = &behaviour.mdns;
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[tokio::test]
    async fn test_node_behaviour_with_custom_config() {
        let keypair = Keypair::generate_ed25519();
        let local_peer_id = keypair.public().to_peer_id();
        let config = BehaviourConfig {
            protocol_version: "/test/1.0.0".to_string(),
            agent_version: "test-agent/0.1.0".to_string(),
            enable_mdns: true,
            enable_nat_traversal: false,
        };

        let result = NodeBehaviour::new(local_peer_id, &keypair, config, None);

        assert!(result.is_ok());
    }

    // Test From implementations for NodeBehaviourEvent
    // These test the event conversion traits

    #[test]
    fn test_from_kad_event() {
        // Create a simple Kademlia event that we can construct
        // kad::Event has several variants; RoutingUpdated is one that's relatively easy to reason about
        // However, creating actual kad::Event instances requires complex setup,
        // so we verify the From implementation exists by type checking
        fn assert_from_impl<T, U>()
        where
            U: From<T>,
        {
        }
        assert_from_impl::<kad::Event, NodeBehaviourEvent>();
    }

    #[test]
    fn test_from_gossipsub_event() {
        fn assert_from_impl<T, U>()
        where
            U: From<T>,
        {
        }
        assert_from_impl::<gossipsub::Event, NodeBehaviourEvent>();
    }

    #[test]
    fn test_from_request_response_event() {
        fn assert_from_impl<T, U>()
        where
            U: From<T>,
        {
        }
        assert_from_impl::<
            request_response::Event<ContentRequest, ContentResponse>,
            NodeBehaviourEvent,
        >();
    }

    #[test]
    fn test_from_identify_event() {
        fn assert_from_impl<T, U>()
        where
            U: From<T>,
        {
        }
        assert_from_impl::<identify::Event, NodeBehaviourEvent>();
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn test_from_mdns_event() {
        fn assert_from_impl<T, U>()
        where
            U: From<T>,
        {
        }
        assert_from_impl::<mdns::Event, NodeBehaviourEvent>();
    }

    #[test]
    fn test_agent_version_contains_package_version() {
        let config = BehaviourConfig::default();
        let pkg_version = env!("CARGO_PKG_VERSION");

        assert!(
            config.agent_version.contains(pkg_version),
            "Agent version '{}' should contain package version '{}'",
            config.agent_version,
            pkg_version
        );
    }
}
