name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt
      - name: Check code formatting
        run: cargo fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "all-targets-profile-test"
      - name: Build
        run: cargo build --workspace --all-targets --profile test

  clippy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal --component clippy
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "all-targets-profile-test"
          save-if: false # Restore only
      - name: Run clippy
        run: cargo clippy --workspace --all-targets --no-deps -- --deny warnings

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "all-targets-profile-test"
          save-if: false # Restore only
      - name: Run tests
        run: cargo test --workspace
